tags:
  - name: Products
paths:
  /:
    get:
      summary: Obtener lista de productos
      parameters:
        - name: limit
          in: query
          description: Número de productos por página
          required: false
          schema:
            type: integer
            default: 10
        - name: page
          in: query
          description: Número de la página
          required: false
          schema:
            type: integer
            default: 1
        - name: sort
          in: query
          description: Campo para ordenar los productos
          required: false
          schema:
            type: string
        - name: query
          in: query
          description: Consulta para filtrar productos
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Lista de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Error interno del servidor
    post:
      summary: Añadir un nuevo producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Producto añadido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '500':
          description: Error interno del servidor
  /{pid}:
    get:
      summary: Obtener producto por ID
      parameters:
        - name: pid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Producto no encontrado
        '500':
          description: Error interno del servidor
    put:
      summary: Actualizar producto por ID
      parameters:
        - name: pid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Producto actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '500':
          description: Error interno del servidor
    delete:
      summary: Eliminar producto por ID
      parameters:
        - name: pid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Producto eliminado
        '500':
          description: Error interno del servidor
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          description: ID del producto
        nombre:
          type: string
          description: Nombre del producto
        descripcion:
          type: string
          description: Descripción del producto
        precio:
          type: number
          description: Precio del producto
        stock:
          type: integer
          description: Cantidad en stock del producto
      required:
        - nombre
        - precio
        - stock